import assert from "node:assert/strict";
import { MATCH_FORMATS } from "../shared/match-formats.js";
import { createMatchState, applyRoundChoice, advanceRound, applyScore, undoScore, setSecondPeriodFirstChooser } from "../shared/match-state.js";
import { isValidAction, updatePositionAfterScore } from "../console/modules/match-scoring.js";
import { validateFinalResult } from "../console/modules/match-summary.js";
import { startClock, stopClock } from "../console/modules/match-timer.js";
import { handleRefProgression } from "../shared/progression-engine.js";
import { pushActionSnapshot, undoAction } from "../console/modules/match-undo.js";
import { createManualRoundGuard } from "../console/modules/manual-round-guard.js";

assert.deepEqual(MATCH_FORMATS.novice_45sec.periods.map(p => p.seconds), [45, 45, 45]);
assert.deepEqual(MATCH_FORMATS.youth_1min.periods.map(p => p.seconds), [60, 60, 60]);
assert.deepEqual(MATCH_FORMATS.jv_90sec.periods.map(p => p.seconds), [90, 90, 90]);
assert.deepEqual(MATCH_FORMATS.jv_consolation.periods.map(p => p.seconds), [60, 90, 90]);
assert.deepEqual(MATCH_FORMATS.varsity_championship.periods.map(p => p.seconds), [120, 120, 120]);
assert.deepEqual(MATCH_FORMATS.varsity_consolation.periods.map(p => p.seconds), [60, 120, 120]);
assert.deepEqual(MATCH_FORMATS.college_3_2_2.periods.map(p => p.seconds), [180, 120, 120]);

const state = createMatchState("novice_45sec");
assert.equal(state.time, 45);
assert.equal(isValidAction("neutral", "athlete", "esc1"), false);
assert.equal(isValidAction("neutral", "athlete", "td3"), true);
applyScore(state, "athlete", 3);
updatePositionAfterScore(state, "athlete", "td3");
assert.equal(state.athleteScore, 3);
assert.equal(state.position, "green_top");
applyScore(state, "opponent", 1);
updatePositionAfterScore(state, "opponent", "esc1");
assert.equal(state.position, "neutral");
undoScore(state, "opponent", 1);
assert.equal(state.opponentScore, 0);

state.currentRound = "1";
let round = advanceRound(state);
assert.equal(round.round, "2");
assert.equal(round.requiresChoice, true);
setSecondPeriodFirstChooser(state, "athlete");
assert.equal(applyRoundChoice(state, "defer"), true);
assert.equal(state.pendingChoice.chooser, "opponent");
assert.equal(applyRoundChoice(state, "bottom"), true);
state.currentRound = "2";
round = advanceRound(state);
assert.equal(round.round, "3");
assert.equal(round.chooser, "athlete");

const tied = createMatchState();
tied.currentRound = "3";
assert.equal(advanceRound(tied).round, "SV1");
tied.currentRound = "SV1";
assert.equal(advanceRound(tied).round, "TB1");
tied.currentRound = "TB1";
assert.equal(advanceRound(tied).round, "TB2");
tied.currentRound = "TB2";
assert.equal(advanceRound(tied).round, "UTB");

assert.equal(validateFinalResult({ athleteScore: 0, opponentScore: 0 }, "athlete", "tech").valid, false);
assert.equal(validateFinalResult({ athleteScore: 7, opponentScore: 0 }, "athlete", "decision").valid, true);
assert.equal(validateFinalResult({ athleteScore: 8, opponentScore: 0 }, "athlete", "major").valid, true);
assert.equal(validateFinalResult({ athleteScore: 15, opponentScore: 0 }, "athlete", "tech").valid, true);
assert.equal(validateFinalResult({ athleteScore: 15, opponentScore: 0 }, "opponent", "tech").valid, false);
assert.equal(validateFinalResult({ athleteScore: 0, opponentScore: 0 }, "athlete", "pin").valid, true);

const refState = createMatchState();
assert.equal(handleRefProgression(refState, "athlete", "stall").points, 0);
assert.equal(handleRefProgression(refState, "athlete", "stall").points, 1);
assert.equal(refState.opponentScore, 1);

const undoState = createMatchState();
undoState.position = "neutral";
const undoEvents = [];
const undoStack = [];
pushActionSnapshot(undoStack, undoState, undoEvents);
applyScore(undoState, "athlete", 3);
updatePositionAfterScore(undoState, "athlete", "td3");
undoEvents.push({ type: "score", side: "athlete", code: "td3", points: 3 });
assert.equal(undoAction(undoStack, undoState, undoEvents), true);
assert.equal(undoState.athleteScore, 0);
assert.equal(undoState.position, "neutral");
assert.equal(undoState.firstScorer, null);
assert.equal(undoState.winner, null);
assert.equal(undoEvents.length, 0);

pushActionSnapshot(undoStack, undoState, undoEvents);
applyScore(undoState, "athlete", 3);
updatePositionAfterScore(undoState, "athlete", "td3");
undoEvents.push({ type: "score", side: "athlete", code: "td3", points: 3 });
pushActionSnapshot(undoStack, undoState, undoEvents);
applyScore(undoState, "opponent", 1);
updatePositionAfterScore(undoState, "opponent", "esc1");
undoEvents.push({ type: "score", side: "opponent", code: "esc1", points: 1 });
assert.equal(undoAction(undoStack, undoState, undoEvents), true);
assert.equal(undoState.opponentScore, 0);
assert.equal(undoState.position, "green_top");
assert.equal(undoState.firstScorer, "athlete");
assert.equal(undoState.winner, "athlete");
assert.equal(undoEvents.length, 1);
assert.equal(undoAction(undoStack, undoState, undoEvents), true);
assert.equal(undoState.athleteScore, 0);
assert.equal(undoState.position, "neutral");
assert.equal(undoState.firstScorer, null);
assert.equal(undoEvents.length, 0);

const undoRefState = createMatchState();
const undoRefEvents = [];
const undoRefStack = [];
pushActionSnapshot(undoRefStack, undoRefState, undoRefEvents);
handleRefProgression(undoRefState, "athlete", "stall");
undoRefEvents.push({ type: "ref", callType: "stall" });
pushActionSnapshot(undoRefStack, undoRefState, undoRefEvents);
handleRefProgression(undoRefState, "athlete", "stall");
undoRefEvents.push({ type: "ref", callType: "stall", points: 1 });
assert.equal(undoRefState.opponentScore, 1);
assert.equal(undoAction(undoRefStack, undoRefState, undoRefEvents), true);
assert.equal(undoRefState.opponentScore, 0);
assert.equal(undoRefState.refProgress.athlete.stalls, 1);
assert.equal(undoRefEvents.length, 1);
assert.equal(undoAction(undoRefStack, undoRefState, undoRefEvents), true);
assert.equal(undoRefState.refProgress.athlete.stalls, 0);
assert.equal(undoRefEvents.length, 0);

let guardNow = 1000;
const roundGuard = createManualRoundGuard({ windowMs: 2500, now: () => guardNow });
assert.equal(roundGuard.request(), false);
assert.equal(roundGuard.isArmed(), true);
guardNow += 1000;
assert.equal(roundGuard.request(), true);
assert.equal(roundGuard.isArmed(), false);
assert.equal(roundGuard.request(), false);
guardNow += 3000;
assert.equal(roundGuard.request(), false);
roundGuard.reset();
assert.equal(roundGuard.isArmed(), false);

const realNow = Date.now;
const realSetInterval = globalThis.setInterval;
const realClearInterval = globalThis.clearInterval;
let now = 1000;
let tick;
let completed = 0;
Date.now = () => now;
globalThis.setInterval = callback => { tick = callback; return 99; };
globalThis.clearInterval = () => {};
const timerState = { time: 45, timer: null };
startClock({ state: timerState, updateClock() {}, saveLocalDraft() {}, publishLiveState() {}, handleRoundComplete() { completed += 1; stopClock({ state: timerState, setStatus() {}, saveLocalDraft() {} }); }, setStatus() {}, formatRoundLabel() { return "R1"; } });
now += 5000;
tick();
assert.equal(timerState.time, 40);
now += 40000;
tick();
assert.equal(timerState.time, 0);
assert.equal(completed, 1);
Date.now = realNow;
globalThis.setInterval = realSetInterval;
globalThis.clearInterval = realClearInterval;

console.log("Match Capture correctness tests: PASS");
